### ISSUE TITLE
GFLOPs, Throughput

### ISSUE THREAD

**Issue by atonyo11** [hulianyuyy/AdaBrowse#1]
Hi author.
Could you provide me with the code for calculating GFLOPs and throughput?

**Comment by hulianyuyy** [comment]
I calculate the GFLOPs manually. While the MACs of the resnet18 backbone can be reffered to [PyTorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter), the FLOPs of 1D CNN, LSTM, classifier and others are mannually computed. As for throughput, you could perform inference with batch size of 1, and the process will report the whole time of processing the Dev or Test set, and thus you could calculate the throughput according to the number of videos in  the Dev or Test set.

**Comment by atonyo11** [comment]
Thanks!

**Comment by atonyo11** [comment]
Sorry, I have one more question.
As I understand, to calculate Gflop, we base on the input. But in this work, input is different for each batch. So how to calculate Gflop?

**Comment by hulianyuyy** [comment]
We calculat the averaged FLOPs per frame, and assume each video has 100 frames to show the results. E.g., the FLOPs per frame is 3.64G, we give 364G as the FLOPs for comparison for the video.

**Comment by atonyo11** [comment]
I got it. Thank you!
