### ISSUE TITLE
Can you list the specific version and dependencies like torch version, c++ and others requirement to install CTCDECODE

### ISSUE THREAD

**Issue by ethio-artifical** [hulianyuyy/AdaBrowse#2]
i am trying to install ctcdecode==0.4 [[parlance/ctcdecode]] from https://github.com/parlance/ctcdecode for beam search decode.
but i could not find the correct specfic version and still i can't install in google colab ,kaggle and in my local machine

**Comment by hulianyuyy** [comment]
According to other users, you should install torch at least 1.13.0, to install ctcdecode. I don't notice the effect of C++ on ctcdecode. You could paste your errors.
